spring.application.name=aromacafe-web

# Puerto de la web (8080 por defecto; lo dejo explicito)
server.port=8080

# URL base de tu API .NET (ajusta el puerto dependiendo de la api)
api.base.url=http://localhost:5053/api